services:
  united-portal:
    build: .
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    depends_on:
      - united-portal-db

  united-portal-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal
    ports:
      - "5432:5432"
